version: '2'
services:
  cassandra:
    image: cassandra
    ports:
     - "7000-7001:7000-7001"
     - "7199:7199"
     - "9042:9042"
     - "9160:9160"
    volumes:
      - ./data/cassandra:/var/lib/cassandra:rw
  redis:
    image: redis
    ports:
     - "6379:6379"